### PR TITLE
Migrate to use env vars instead of fixed test organization

### LINKED ISSUE #394: Add environment variable for testing with repos
Replace `gitHubTestOrg   = "autograder-test"` with environment variable `QUICKFEED_TEST_REPO` in all relevant tests.

### PR DESCRIPTION
**Pull request by meling**
This allows use of QF_TEST_ORG and documents various other uses of env vars for tests.

Fixes #394.

### CODE REVIEW

File: assignments/assignments_test.go [hunk 1]
```diff
@@ -10,44 +10,34 @@ import (
...
-	gitHubTestOrgID = 30462712
-)
-
-// To enable this test, please see instructions in the developer guide (dev.md).
-// You will also need access to the autograder-test organization; you may request
-// access by sending your GitHub username to hein.meling at uis.no.
+// To run this test, please see instructions in the developer guide (dev.md).
 
 func TestFetchAssignments(t *testing.T) {
+	qfTestOrg := os.Getenv("QF_TEST_ORG")
```
Comment (meling) [inline assignments/assignments_test.go:16]: Note to self. Make test helpers that are accessible from all packages to ensure consistent use of these variables and appropriate message logging.

File: ci/run_tests_test.go [hunk 2]
```diff
@@ -12,17 +12,25 @@ import (
 )
 
 const (
-	// qf101 is a test course for experimenting with go.sh behavior.
-	// The test below will run locally on the test machine, not on the QuickFeed machine.
-	getURL  = "https://github.com/qf101/meling-labs.git"
-	testURL = "https://github.com/qf101/tests.git"
+	gh         = "github.com"
+	qf101      = "qf101"
+	ghUserName = "meling"
```
Comment (meling) [inline ci/run_tests_test.go:17]: Fetch `GITHUB_USER` from the environment, and fallback to `USER` if not defined.

**Review by 0xf8f8ff — APPROVED** [review]
